<a href="https://colab.research.google.com/github/mr-cri-spy/Deep-Learning-projects/blob/main/deep_learning_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing library

In [ ]:
import numpy as np

creating  the x and y

In [ ]:
x = np.array([[1,0,0],[0,0,1],[1,0,1],[1,1,1]])
y = np.array([[1],[0],[1],[1]])

In [ ]:
x

array([[1, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
y

array([[1],
       [0],
       [1],
       [1]])

assighn the weights

In [ ]:
np.random.seed(20)
weight = np.random.random([3,1])
weight

array([[0.5881308 ],
       [0.89771373],
       [0.89153073]])

weighted sum

In [ ]:
sum = np.dot(x,weight) + 0.02
sum

array([[0.6081308 ],
       [0.91153073],
       [1.49966153],
       [2.39737526]])

Activation function(sigmoid bec which is taken only 0 or 1 right so )

In [ ]:
yp = 1/(1 + np.exp(-sum))
yp

array([[0.64751429],
       [0.7133133 ],
       [0.81752399],
       [0.91662693]])

initially we will get wrong prediction bec weight is not correct but we have to correct, tune  the weight now the correct o/p we are accepting is 1,0,1,1

In [ ]:
yp.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

we have to calculate error right now

In [ ]:
error = y - yp
error

array([[ 0.35248571],
       [-0.7133133 ],
       [ 0.18247601],
       [ 0.08337307]])

Gradient descent ( Optimize the model )

In [ ]:
sum = np.dot(x,weight) + 0.02
yp = 1/(1 + np.exp(-sum))
error = y - yp
change_in_weight = error * yp *(1-yp) ##gradient descent

weight =weight + np.dot(x.T,change_in_weight)

error ## now error will be reduce

array([[ 0.26542112],
       [-0.61252056],
       [ 0.1890953 ],
       [ 0.0847886 ]])

run 1000 times lets see


In [ ]:
for i in range(1000):
  sum = np.dot(x,weight) + 0.02
  yp = 1/(1 + np.exp(-sum))
  error = y - yp
  change_in_weight = error * yp *(1-yp) ##gradient descent
  weight =weight + np.dot(x.T,change_in_weight)



In [ ]:

error

array([[ 0.00141774],
       [-0.04131824],
       [ 0.03251447],
       [ 0.00796023]])

In [ ]:
y

array([[1],
       [0],
       [1],
       [1]])

In [ ]:
yp.round()

array([[1.],
       [0.],
       [1.],
       [1.]])

In [ ]:
weight ##true bec y is depending on  x

array([[ 6.53835812],
       [ 1.43235297],
       [-3.16480617]])