<a href="https://colab.research.google.com/github/mr-cri-spy/Deep-Learning-projects/blob/main/Spam_Email_Classificstion_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.layers import LSTM,Dense,Dropout,Embedding
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

In [ ]:
data = pd.read_csv("/content/spam.csv",encoding='latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
data['v1'].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
x = data['v2']
y = data['v1']
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.85,random_state=7)

In [ ]:
tok = Tokenizer(num_words=1000)
tok.fit_on_texts(xtrain)
sequences = tok.texts_to_sequences(xtrain)
sequences_mat = pad_sequences(sequences,maxlen=150,padding="pre")
sequences_mat

array([[  0,   0,   0, ...,   0, 155, 447],
       [  0,   0,   0, ...,   2,  28, 113],
       [  0,   0,   0, ...,  38,  44,   4],
       ...,
       [  0,   0,   0, ...,  52,   2,  28],
       [  0,   0,   0, ..., 193, 249,  97],
       [  0,   0,   0, ...,   2,  31, 531]], dtype=int32)

In [ ]:
sequences_mat[100]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,  83,  79,  16, 102], dtype=int32)

In [ ]:
tok.word_index

{'i': 1,
 'to': 2,
 'you': 3,
 'a': 4,
 'the': 5,
 'u': 6,
 'and': 7,
 'in': 8,
 'is': 9,
 'me': 10,
 'my': 11,
 'for': 12,
 'your': 13,
 'it': 14,
 'of': 15,
 'call': 16,
 'have': 17,
 'on': 18,
 '2': 19,
 'are': 20,
 'that': 21,
 'now': 22,
 'so': 23,
 'but': 24,
 'not': 25,
 'or': 26,
 'can': 27,
 'do': 28,
 'at': 29,
 'will': 30,
 'get': 31,
 "i'm": 32,
 'ur': 33,
 'be': 34,
 'no': 35,
 'if': 36,
 'with': 37,
 'we': 38,
 'just': 39,
 'this': 40,
 '4': 41,
 'gt': 42,
 'lt': 43,
 'up': 44,
 'when': 45,
 'go': 46,
 'from': 47,
 'free': 48,
 'all': 49,
 'ok': 50,
 'how': 51,
 'what': 52,
 'out': 53,
 'good': 54,
 'know': 55,
 'then': 56,
 'like': 57,
 'got': 58,
 'was': 59,
 'its': 60,
 'am': 61,
 'day': 62,
 'only': 63,
 'come': 64,
 'there': 65,
 'time': 66,
 'love': 67,
 'text': 68,
 'he': 69,
 'send': 70,
 'want': 71,
 'txt': 72,
 'as': 73,
 'home': 74,
 'one': 75,
 'lor': 76,
 'by': 77,
 'going': 78,
 "i'll": 79,
 'see': 80,
 'still': 81,
 'need': 82,
 'sorry': 83,
 'about': 84,
 

In [ ]:
from keras.models import Sequential
model = Sequential()
model.add(Embedding(1000,10,input_length=150))
model.add(LSTM(64))
model.add(Dense(256,activation='relu'))  ## hidden layer
model.add(Dropout(0.5))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.fit(sequences_mat,ytrain,batch_size=64,epochs=15)

Epoch 1/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8508 - loss: 0.4275
Epoch 2/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9644 - loss: 0.1403
Epoch 3/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9825 - loss: 0.0597
Epoch 4/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9845 - loss: 0.0527
Epoch 5/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9888 - loss: 0.0410
Epoch 6/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9887 - loss: 0.0440
Epoch 7/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9923 - loss: 0.0284
Epoch 8/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9915 - loss: 0.0227
Epoch 9/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9951 - loss: 0.0183
Epoch 10/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9927 - loss: 0.0669
Epoch 11/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9944 - loss: 0.0209
Epoch 12/15
74/74 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9904 - 

In [ ]:
text_sequences = tok.texts_to_sequences(xtest)
test_sequences_mat = pad_sequences(text_sequences,maxlen=150,padding="pre")

In [ ]:
model.evaluate(test_sequences_mat,ytest)

27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9851 - loss: 0.0823


[0.0455554760992527, 0.9904305934906006]

In [ ]:
ypred = model.predict(test_sequences_mat)
ypred = ypred.round()
ypred

27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(ytest,ypred)
ac = accuracy_score(ytest,ypred)
print(ac)
print(cm)

0.9904306220095693
[[722   1]
 [  7 106]]


In [ ]:
### Test a new sample
txt = ["You got a 50% discount and free of cost hampers in every purchase",
       "Congratulations, you are selected for the applied job"]
txt = tok.texts_to_sequences(txt)
txt = pad_sequences(txt,maxlen=150,padding="pre")
model.predict(txt).round()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[1.],
       [0.]], dtype=float32)